defaultPortal: Varun-hubspot
portals:
  - name: Varun-hubspot
    portalId: 39706227
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CMms9faAMRIOAAUAQAAAAGwAQAJYAgEY87z3EiDSrboYKO7pDDIUw-3wMSZ0bwUK7kGtO2mbbLLhlqk6MAAABEEAAAAAAAAAAAAAAAAAgAAAAAAABAAAAAAAAAAAPGBQAABEAABA_BgGABAgA0IUN_CwWz-P7yuxaJgbJnczK-EWt7tKA25hMVIAWgA
        expiresAt: '2023-05-12T07:29:26.623Z'
    personalAccessKey: >-
      CiQ2MzBhMjViMy00MjU4LTRiY2MtYmU1Yi1hZGMyOWEzMzdjMDAQ87z3EhjSrboYKhkABeaRgv9ujpNpH1WkdKvvSN4QqRMEwlbQSgNuYTE
    sandboxAccountType: null
    parentAccountId: null
