defaultPortal: Varun-hubspot
portals:
  - name: Varun-hubspot
    portalId: 39706227
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CJTpqfmAMRIOAAUAQAAAAGwAQAJYAgEY87z3EiDSrboYKO7pDDIU0LUZ3hHCIf4aLgCJapp8mtMaSTM6MAAABEEAAAAAAAAAAAAAAAAAgAAAAAAABAAAAAAAAAAAPGBQAABEAABA_BgGABAgA0IUIAZOIfJHC8dimdgIni9VPQx-C55KA25hMVIAWgA
        expiresAt: '2023-05-12T08:53:40.651Z'
    personalAccessKey: >-
      CiQ2MzBhMjViMy00MjU4LTRiY2MtYmU1Yi1hZGMyOWEzMzdjMDAQ87z3EhjSrboYKhkABeaRgv9ujpNpH1WkdKvvSN4QqRMEwlbQSgNuYTE
    sandboxAccountType: null
    parentAccountId: null
